from app.core.dao.book import *
from app.core.dao.certificate import *
from app.core.dao.college import *
from app.core.dao.innovation_project import *
from app.core.dao.invigilate import *
from app.core.dao.reform_paper import *
from app.core.dao.reform_project import *
from app.core.dao.student import *
from app.core.dao.teacher import *
