from app.dao.book import *
from app.dao.certificate_info import *
from app.dao.college import *
from app.dao.innovation_project import *
from app.dao.invigilate_info import *
from app.dao.reform_paper import *
from app.dao.reform_project import *
from app.dao.student import *
from app.dao.teacher import *