from app.core.auth import *
from app.core.book import *
from app.core.certificate_info import *
from app.core.college import *
from app.core.innovation_project import *
from app.core.invigilate_info import *
from app.core.reform_paper import *
from app.core.reform_project import *
from app.core.student import *
from app.core.teacher import *